
set(SOURCES "")
list(APPEND SOURCES Luna/Canvas.c Luna/Canvas.h)
list(APPEND SOURCES Luna/Clock.c Luna/Clock.h)
list(APPEND SOURCES Luna/Deque.c Luna/Deque.h)
list(APPEND SOURCES Luna/Event.c  Luna/Event.h)
list(APPEND SOURCES Luna/Font.c  Luna/Font.h)
list(APPEND SOURCES Luna/Result.c Luna/Result.h)
list(APPEND SOURCES Luna/Memory.c Luna/Memory.h)
list(APPEND SOURCES Luna/Pixels.c Luna/Pixels.h)
list(APPEND SOURCES Luna/Blend/Copy.c Luna/Blend/Copy.h)
list(APPEND SOURCES Luna/Blend/SourceOver.c Luna/Blend/SourceOver.h)

IF (WIN32)
  list(APPEND SOURCES Luna/Windows/BackBuffer.c Luna/Windows/BackBuffer.h)
  add_executable(LunaDemo001 WIN32 Test001.c ${SOURCES} Resources.rc)
  add_compile_definitions(Luna_Configuration_Windows)
ELSE()
  list(APPEND SOURCES Luna/Linux/BackBuffer.c Luna/Linux/BackBuffer.h)
  add_executable(LunaDemo001 Test001.c ${SOURCES})
  add_compile_definitions(Luna_Configuration_Linux)
ENDIF()

target_include_directories(LunaDemo001 PRIVATE ${CMAKE_CURRENT_SOURCE_DIR})

IF (WIN32)
  add_compile_definitions(Luna_Configuration_Windows)
ELSE()
  add_compile_definitions(Luna_Configuration_Linux)
ENDIF()
